version: '3'

services:
  # Database
  db:
    container_name: stationfive-db
    image: mysql:5.7
    volumes:
      - ~/.stationfive-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stationfive
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: stationfive-db-admin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    volumes:
      - ~/.stationfive-db-admin/sessions:/sessions
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    container_name: stationfive-wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: